version: '2.4'
services:
  beverage_delivery_manager:
    build: .
    mem_limit: 300m
    restart: always
    ports:
      - 5000:5000
  mongo:
    image: mongo:4.0.12
    ports:
      - 27017:27017
    volumes:
      - $PWD:/imports
  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 8081:8081