// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import (
	domain "beverage_delivery_manager/pdv/domain"

	mock "github.com/stretchr/testify/mock"
)

// PdvCache is an autogenerated mock type for the PdvCache type
type PdvCache struct {
	mock.Mock
}

// FindByAddress provides a mock function with given fields: point
func (_m *PdvCache) FindByAddress(point domain.Point) (domain.Pdv, error) {
	ret := _m.Called(point)

	var r0 domain.Pdv
	if rf, ok := ret.Get(0).(func(domain.Point) domain.Pdv); ok {
		r0 = rf(point)
	} else {
		r0 = ret.Get(0).(domain.Pdv)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.Point) error); ok {
		r1 = rf(point)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ID
func (_m *PdvCache) FindByID(ID string) (domain.Pdv, error) {
	ret := _m.Called(ID)

	var r0 domain.Pdv
	if rf, ok := ret.Get(0).(func(string) domain.Pdv); ok {
		r0 = rf(ID)
	} else {
		r0 = ret.Get(0).(domain.Pdv)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: key, pdv
func (_m *PdvCache) Save(key string, pdv domain.Pdv) error {
	ret := _m.Called(key, pdv)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, domain.Pdv) error); ok {
		r0 = rf(key, pdv)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
