// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"beverage_delivery_manager/pdv/domain"
)

type PdvAddressInput struct {
	Longitude float64 `json:"longitude"`
	Latitude  float64 `json:"latitude"`
}

type PdvIDInput struct {
	ID string `json:"id"`
}

type PdvInput struct {
	TradingName  string              `json:"tradingName"`
	OwnerName    string              `json:"ownerName"`
	Document     string              `json:"document"`
	CoverageArea domain.MultiPolygon `json:"coverageArea"`
	Address      domain.Point        `json:"address"`
}
