name: Go

on:
  push:
    branches-ignore: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15.4
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

      - name: Get dependencies
        run: |
          go mod download
      - name: Build
        run: make build

      - name: Test
        run: make test
